modLoader="javafml"
loaderVersion="[45,)"
issueTrackerURL="https://github.com/JDKDigital/productive-bees/issues"
license="ARR"

[[mods]] #mandatory
modId="productivebees"
version="${file.jarVersion}"
displayName="Productive Bees"
# displayURL="http://example.com/"
logoFile="logo.png"
credits="Thanks to me"
authors="LobsterJonn"
description='''
Useful bees
'''

[[dependencies.productivebees]] #optional
    modId="forge"
    mandatory=true
    versionRange="[45,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.productivebees]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.4,1.20)"
    ordering="NONE"
    side="BOTH"
